// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {mkv} from '../models';
import {main} from '../models';

export function AppInfo():Promise<string>;

export function Cancel():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function ListModels():Promise<Array<string>>;

export function Log(arg1:string):Promise<void>;

export function Progress(arg1:number,arg2:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanTracks(arg1:string):Promise<Array<mkv.Track>>;

export function SelectVideo():Promise<string>;

export function StartTranslation(arg1:main.TranslateRequest):Promise<void>;
